### ISSUE TITLE
Deploy issue

### ISSUE THREAD

**Issue by Rohanthakur360** [kozyol/OnlineSimBot#4]
Bro is bot ko kha deploy karo please heroku deployable banoo

**Comment by Kourva** [comment]
Hi @Rohanthakur360 

Bot ko Heroku par deploy karne ke liye, aapko project ki mukhya nirdeshika mein `Procfile` naamak file banani hogi aur use save karna hoga. Procfile ki samagri mein bot ke liye karyakarta prakriya shuru karne ke liye nirdisht karna chahiye.

```Procfile
worker: python main.py
```

Deployment prakriya ke saath aur adhik sahayata ki avashyakta ho to kripya mujhse sampark karein.

Tumhara directory is tarah se dikhega:
```
.
├── LICENSE
├── main.py
├── README.md
├── requirements.txt
├── Procfile
└── src
    ├── token.txt
    ├── utils.py
    └── vneng.py

```
